use Assignment2DB

select * from EMPLOYEE

CREATE or ALTER PROCEDURE EmployeePayslip (@EMPNO INT)
AS
BEGIN
   DECLARE @SALARY DECIMAL(8, 2)
   DECLARE @HRA DECIMAL(8, 2)
   DECLARE @DA DECIMAL(8, 2)
   DECLARE @PF DECIMAL(8, 2)
   DECLARE @IT DECIMAL(8, 3)
   DECLARE @DEDUCTIONS DECIMAL(8, 2)
   DECLARE @GROSS_SALARY DECIMAL(8, 2)
   DECLARE @NET_SALARY DECIMAL(8, 2)

   SELECT @SALARY = SAL FROM EMPLOYEE WHERE EMPNO = @EMPNO

   SELECT @HRA = @SALARY * 0.10
   SELECT @DA = @SALARY * 0.20
   SELECT @PF = @SALARY * 0.08
   SELECT @IT = @SALARY * 0.05

   --Deductions as sum of PF and IT
   SELECT @DEDUCTIONS = @PF + @IT

   --Gross Salary as sum of SAL,HRA,DA 
   SELECT @GROSS_SALARY = @SALARY + @HRA + @DA

   --Net salary as  Gross salary- Deduction
   SELECT @NET_SALARY = @GROSS_SALARY - @DEDUCTIONS

   SELECT EMPNO, EMPNAME, @SALARY AS SALARY, @HRA AS HRA, @DA AS DA, @PF AS PF, @IT AS IT, @DEDUCTIONS AS Deductions, @GROSS_SALARY AS 'Gross Salary', @NET_SALARY AS 'NetSalary'
   FROM EMPLOYEE
   WHERE EMPNO = @EMPNO
END

EXECUTE EmployeePayslip @EMPNO = 7521;